import { useEffect, useMemo, useState } from 'react';
import { familyById, productById } from '../data/catalog';
import { productionStages } from '../data/productionStages';
import { buildModelComparison, comparableProducts } from '../domain/comparison';
import { useExplorer } from '../state/ExplorerProvider';
import { track } from '../analytics/events';

export function ComparisonWorkbench() {
  const { state, dispatch } = useExplorer();
  const [isMobile, setIsMobile] = useState(() => typeof window !== 'undefined' && window.innerWidth < 768);
  const product = state.comparisonProductId ? productById.get(state.comparisonProductId) : undefined;
  const selectionLimit = isMobile ? 2 : 3;
  const capacities = product?.models.flatMap((model) => model.children ?? []) ?? [];
  const candidates = state.comparisonLevel === 'capacities' ? capacities : product?.models ?? [];
  useEffect(() => { const resize = () => setIsMobile(window.innerWidth < 768); window.addEventListener('resize', resize); return () => window.removeEventListener('resize', resize); }, []);
  useEffect(() => { dispatch({ type: 'LIMIT_COMPARISON_MODELS', limit: selectionLimit }); }, [dispatch, selectionLimit]);
  const selectedModels = candidates.filter((model) => state.comparisonModelIds.includes(model.id));
  const modelKey = selectedModels.map((model) => model.id).join('|');
  const sections = useMemo(() => product && modelKey ? buildModelComparison(product, modelKey.split('|')) : [], [product, modelKey]);
  const visibleSections = sections.map((section) => ({ ...section, rows: state.comparisonShowDifferences ? section.rows.filter((row) => row.differs) : section.rows }));
  const rowCount = visibleSections.reduce((total, section) => total + section.rows.length, 0);
  const technicalCount = visibleSections.find((section) => section.id === 'technical')?.rows.length ?? 0;
  const recordCountLabel = (item: typeof comparableProducts[number]) => { const count = item.models.flatMap((model) => model.children ?? []).length; return count ? `${item.models.length} series · ${count} capacity options` : `${item.models.length} models / variants`; };
  return <div className="comparison-view">
    <div className="view-intro"><div><p className="proof-label">Model Comparison</p><h3>Compare Models Within One Product</h3></div><p>Choose a product, then compare its models or variants side by side. The table includes every available specification for your selections. A larger numerical value does not establish suitability.</p></div>
    <section className="comparison-setup" aria-labelledby="comparison-product-heading"><div className="comparison-step"><span>01</span><div><h4 id="comparison-product-heading">Choose a Product</h4><p>Products with two or more models, variants or series are available here.</p></div></div><label className="comparison-product-select"><span>Product</span><select value={product?.id ?? ''} onChange={(event) => { dispatch({ type: 'SET_COMPARISON_PRODUCT', productId: event.target.value || null }); track('comparison_viewed', { mode: 'models', ids: event.target.value ? [event.target.value] : [] }); }}><option value="">Select a Product to Compare</option>{comparableProducts.map((item) => <option value={item.id} key={item.id}>{item.name} ({recordCountLabel(item)})</option>)}</select></label></section>
    {!product && <div className="empty-state"><span className="status-icon" aria-hidden="true">+</span><h3>Choose a Product to Begin</h3><p>The model choices and technical specifications will appear here.</p></div>}
    {product && <>
      <section className="comparison-context" aria-label="Selected Product"><div><p className="proof-label">{familyById.get(product.familyId)?.name}</p><h4>{product.name}</h4><p>{product.primaryFunction}</p></div><dl><div><dt>Where It Fits</dt><dd>{product.stages.map((id) => productionStages.find((stage) => stage.id === id)?.label).join(' · ')}</dd></div><div><dt>Selection Factors</dt><dd>{product.selectionFactors.join(' · ')}</dd></div></dl><button type="button" className="text-button" onClick={() => dispatch({ type: 'OPEN_DRAWER', productId: product.id })}>View Product Details</button></section>
      <section className="model-selector" aria-labelledby="model-selector-heading"><div className="comparison-step"><span>02</span><div><h4 id="model-selector-heading">Choose Models or Variants</h4><p>Select up to {selectionLimit} options. Smaller screens show up to two options. When switching to a smaller screen, the first two selections are kept.</p></div></div>
        {capacities.length > 0 && <fieldset className="comparison-level"><legend>Compare Series or Capacity Options</legend><label className={state.comparisonLevel === 'models' ? 'is-selected' : ''}><input type="radio" name="comparison-level" checked={state.comparisonLevel === 'models'} onChange={() => dispatch({ type: 'SET_COMPARISON_LEVEL', level: 'models' })} /><span>Loadcell Series</span></label><label className={state.comparisonLevel === 'capacities' ? 'is-selected' : ''}><input type="radio" name="comparison-level" checked={state.comparisonLevel === 'capacities'} onChange={() => dispatch({ type: 'SET_COMPARISON_LEVEL', level: 'capacities' })} /><span>Capacity Options</span></label></fieldset>}
        <div className="model-choice-grid">{candidates.map((model) => { const checked = state.comparisonModelIds.includes(model.id); return <label className={checked ? 'is-selected' : ''} key={model.id}><input type="checkbox" checked={checked} disabled={!checked && selectedModels.length >= selectionLimit} onChange={() => dispatch({ type: 'TOGGLE_COMPARISON_MODEL', modelId: model.id, limit: selectionLimit })} /><strong>{model.name}</strong><small>{model.specs.length} Technical Specifications</small></label>; })}</div><p className="selection-note" aria-live="polite">{selectedModels.length} {selectedModels.length === 1 ? 'Model or Variant' : 'Models or Variants'} Selected.</p>
      </section>
      {selectedModels.length > 0 ? <section className="comparison-output" aria-labelledby="comparison-output-heading"><div className="comparison-output-header"><div className="comparison-step"><span>03</span><div><h4 id="comparison-output-heading">Review Technical Specifications</h4><p>{technicalCount} technical parameters, plus availability and selection conditions, across {selectedModels.length} selected model{selectedModels.length === 1 ? '' : 's'}.</p></div></div><label className="check-control"><input type="checkbox" checked={state.comparisonShowDifferences} onChange={(event) => dispatch({ type: 'SET_COMPARISON_DIFFERENCES', show: event.target.checked })} /><span>Show Differences Only</span></label></div>
        {rowCount ? <><div className="comparison-table-wrap" tabIndex={0} aria-label="Scrollable Model Comparison"><table className="comparison-table"><caption>{product.name}: Model Specification Comparison</caption><thead><tr><th scope="col">Technical Parameter</th>{selectedModels.map((model) => <th scope="col" key={model.id}>{model.name}</th>)}</tr></thead>{visibleSections.map((section) => section.rows.length > 0 && <tbody key={section.id}><tr className="comparison-section-row"><th scope="rowgroup" colSpan={selectedModels.length + 1}>{section.label}</th></tr>{section.rows.map((row) => <tr key={row.key}><th scope="row">{row.label}</th>{selectedModels.map((model) => <td key={model.id}>{row.values[model.id]}</td>)}</tr>)}</tbody>)}</table></div><div className="comparison-mobile-table" aria-label={`${product.name} Mobile Model Comparison`}>{visibleSections.map((section) => section.rows.length > 0 && <section key={section.id}><h5>{section.label}</h5>{section.rows.map((row) => <article key={row.key}><h6>{row.label}</h6><dl>{selectedModels.map((model) => <div key={model.id}><dt>{model.name}</dt><dd>{row.values[model.id]}</dd></div>)}</dl></article>)}</section>)}</div></> : <div className="empty-state compact"><h4>No Differing Parameters in the Selected Set</h4><p>Turn off “Show Differences Only” to review all specifications.</p></div>}
        <p className="comparison-disclaimer">An em dash (—) means a specification is available for another selected model, but no value is available for this model. Parameters without a value for any selected model are omitted. Final selection requires Puretronics application review.</p>
      </section> : <div className="empty-state compact"><h3>Select at Least One Model</h3><p>Choose models above to see their technical specifications.</p></div>}
      <div className="comparison-footer"><button type="button" className="text-button" onClick={() => dispatch({ type: 'CLEAR_COMPARISON' })}>Clear Model Comparison</button><a className="button" href="#prepare" onClick={() => dispatch({ type: 'ADD_SELECTED', productId: product.id })}>Prepare a Review for {product.shortName}</a></div>
    </>}
  </div>;
}
