import { siteConfig } from '../config/site';
import { track } from '../analytics/events';

const steps = [['01', 'Explore', 'Start with the problem, production stage, product family or known product.'], ['02', 'Narrow', 'Review relevant capabilities and compare models within one product.'], ['03', 'Prepare', 'Organise known operating conditions, integration requirements and open questions.'], ['04', 'Review', 'Discuss the application with Puretronics and agree the most useful next step.']];

export function ProofAndCertificate() {
  return (
    <>
      <section className="section section-band pathway-section"><div className="container"><p className="eyebrow">From Requirement to the Right Next Step</p><h2>A Clearer Route From Broad Requirement to Focused Review.</h2><div className="pathway-grid">{steps.map(([number, title, copy]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{copy}</p></article>)}</div>
        <div className="review-context-grid"><section><h3>What an Application Review Can Cover</h3><ul><li>The Production, Quality-Control or Testing Objective</li><li>The Present Process, Equipment or Limitation</li><li>Relevant Puretronics Capability and Product Paths</li><li>Operating Range, Speed, Load, Voltage, Method or Environmental Inputs</li><li>New-Line, Retrofit, Laboratory or OEM Context</li><li>Drawings, Samples, Specifications or Photographs</li><li>Information Needed to Narrow Equipment or Configuration</li></ul></section><section><h3>Who the Review Is Designed For</h3><ul><li>Plant, Operations and Business Leaders</li><li>Production, Process and Extrusion Engineers</li><li>QA, QC and Laboratory Teams</li><li>Automation, Electrical and Maintenance Teams</li><li>Procurement and Project Teams</li><li>Cable-Line OEMs, Machine Builders and Integration Partners</li></ul></section></div>
      </div></section>
      <section className="section evidence-section" id="technical-evidence"><div className="container"><p className="eyebrow">Technical Information for Equipment Selection</p><h2>Understand the Specifications That Matter to Your Application.</h2><p className="section-lead">Open a product in the Capability Explorer for its applications, model specifications, accessories and installation considerations. Compare models to examine operating ranges and technical differences.</p><div className="review-context-grid"><section><h3>Check the Complete Operating Combination</h3><p>Diameter, speed, voltage, temperature, capacity and mounting requirements must be assessed together. A match on one value does not establish suitability for the complete application.</p></section><section><h3>Confirm Configuration With Puretronics</h3><p>Bring relevant drawings, sample details, test procedures and operating conditions. Puretronics can review the required equipment, interfaces, options and any application-specific conditions before final selection.</p><a className="text-link" href="#explore" onClick={() => track('technical_resource_opened', { location: 'technical-information' })}>Explore Product Specifications →</a></section></div></div></section>
      <section className="section section-cool" id="service-support"><div className="container about-grid"><div><p className="eyebrow">About Puretronics</p><h2>Wire and Cable Production and Validation Capabilities Since 1990.</h2><p className="section-lead">Puretronics provides the measurement, testing, process-equipment, tension, control and braking capabilities represented in this profile.</p></div><aside><h3>Existing Equipment or a Service Requirement?</h3><p>For service, spares, calibration, commissioning or support relating to an existing installation, use the dedicated route.</p><a className="button button-secondary" href={siteConfig.serviceSupportUrl} onClick={() => track('service_support_cta_clicked', { location: 'service-section' })}>Go to Service and Support</a></aside></div></section>
    </>
  );
}
