import { siteConfig } from '../config/site';
import { track } from '../analytics/events';

const steps = [['01', 'Explore', 'Start with the problem, production stage, product family or known product.'], ['02', 'Narrow', 'Review relevant capability paths and compare approved models within a Primary Product.'], ['03', 'Prepare', 'Organise known operating conditions, integration requirements and open questions.'], ['04', 'Review', 'Meet Puretronics to examine the application and agree the most useful next step.']];
const evidenceNeeds = ['Wire and Cable Application Example', 'Inline Measurement Outcome', 'Spark-Testing Application', 'Tension/Braking Application', 'Customer Testimonial Document'];

export function ProofAndCertificate() {
  return (
    <>
      <section className="section section-band pathway-section"><div className="container"><p className="eyebrow">From Requirement to the Right Next Step</p><h2>A Clearer Route From Broad Requirement to Focused Review.</h2><div className="pathway-grid">{steps.map(([number, title, copy]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{copy}</p></article>)}</div>
        <div className="review-context-grid"><section><h3>What an Application Review Can Cover</h3><ul><li>The Production, Quality-Control or Testing Objective</li><li>The Present Process, Equipment or Limitation</li><li>Relevant Puretronics Capability and Product Paths</li><li>Operating Range, Speed, Load, Voltage, Method or Environmental Inputs</li><li>New-Line, Retrofit, Laboratory or OEM Context</li><li>Drawings, Samples, Specifications or Photographs</li><li>Information Needed to Narrow Equipment or Configuration</li></ul></section><section><h3>Who the Review Is Designed For</h3><ul><li>Plant, Operations and Business Leaders</li><li>Production, Process and Extrusion Engineers</li><li>QA, QC and Laboratory Teams</li><li>Automation, Electrical and Maintenance Teams</li><li>Procurement and Project Teams</li><li>Cable-Line OEMs, Machine Builders and Integration Partners</li></ul></section></div>
      </div></section>
      <section className="section evidence-section" id="technical-evidence"><div className="container evidence-grid"><div><p className="eyebrow">Technical Evidence Where It Matters</p><h2>Validated Information at the Level Where It Supports a Decision.</h2><p className="section-lead">Product roles, approved ranges, model distinctions, production-stage fit, selection factors and caveats remain connected to their governed records.</p><div className="certificate-card"><img src="./assets/documents/puretronics-iso-9001-2015-preview.png" width="992" height="1403" loading="lazy" alt="Preview of the Puretronics ISO 9001:2015 certificate document" /><div><span className="proof-label">Document Artifact</span><h3>ISO 9001:2015 Certificate</h3><p>This supplied certificate is reproduced without alteration. The document shows its own issue and validity information; no current-certification claim is implied.</p><a className="button button-secondary" href={siteConfig.certificateUrl} target="_blank" rel="noreferrer" onClick={() => track('technical_resource_opened', { location: 'certificate' })}>View Certificate <span className="sr-only">(opens in a new tab)</span></a></div></div></div>
        <aside className="evidence-placeholder"><p className="proof-label">Evidence Requested for Client Review</p><h3>Application Proof Module</h3><p>Approved Puretronics application evidence to be added following client review.</p><ul>{evidenceNeeds.map((item) => <li key={item}><span aria-hidden="true">□</span>{item}</li>)}</ul><small>Placeholder items are excluded from structured data and can be removed without changing the page architecture.</small></aside>
      </div></section>
      <section className="section section-cool" id="service-support"><div className="container about-grid"><div><p className="eyebrow">About Puretronics</p><h2>Wire and Cable Production and Validation Capabilities Since 1990.</h2><p className="section-lead">Puretronics provides the measurement, testing, process-equipment, tension, control and braking capabilities represented in this profile.</p></div><aside><h3>Existing Equipment or a Service Requirement?</h3><p>For service, spares, calibration, commissioning or support relating to an existing installation, use the dedicated route.</p><a className="button button-secondary" href={siteConfig.serviceSupportUrl} onClick={() => track('service_support_cta_clicked', { location: 'service-section' })}>Go to Service and Support</a></aside></div></section>
    </>
  );
}
