import { siteConfig } from '../config/site';
import { track } from '../analytics/events';

const steps = [['01', 'Explore', 'Start with the problem, production stage, product family or known product.'], ['02', 'Narrow', 'Review relevant capability paths and compare applicable products or models.'], ['03', 'Prepare', 'Organise known operating conditions, integration requirements and open questions.'], ['04', 'Review', 'Meet Puretronics to examine the application and agree the most useful next step.']];
const evidenceNeeds = ['Wire and cable application example', 'Inline measurement outcome', 'Spark-testing application', 'Tension/braking application', 'Customer testimonial document'];

export function ProofAndCertificate() {
  return (
    <>
      <section className="section section-band pathway-section"><div className="container"><p className="eyebrow">From Requirement to the Right Next Step</p><h2>A clearer route from broad requirement to focused review.</h2><div className="pathway-grid">{steps.map(([number, title, copy]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{copy}</p></article>)}</div>
        <div className="review-context-grid"><section><h3>What an Application Review can cover</h3><ul><li>The production, quality-control or testing objective</li><li>The present process, equipment or limitation</li><li>Relevant Puretronics capability and product paths</li><li>Operating range, speed, load, voltage, method or environmental inputs</li><li>New-line, retrofit, laboratory or OEM context</li><li>Drawings, samples, specifications or photographs</li><li>Information needed to narrow equipment or configuration</li></ul></section><section><h3>Who the review is designed for</h3><ul><li>Plant, operations and business leaders</li><li>Production, process and extrusion engineers</li><li>QA, QC and laboratory teams</li><li>Automation, electrical and maintenance teams</li><li>Procurement and project teams</li><li>Cable-line OEMs, machine builders and integration partners</li></ul></section></div>
      </div></section>
      <section className="section evidence-section" id="technical-evidence"><div className="container evidence-grid"><div><p className="eyebrow">Technical evidence where it matters</p><h2>Validated information at the level where it supports a decision.</h2><p className="section-lead">Product roles, approved ranges, model distinctions, production-stage fit, selection factors and caveats remain connected to their governed records.</p><div className="certificate-card"><img src="./assets/documents/puretronics-iso-9001-2015-preview.png" width="992" height="1403" loading="lazy" alt="Preview of the Puretronics ISO 9001:2015 certificate document" /><div><span className="proof-label">Document artifact</span><h3>ISO 9001:2015 Certificate</h3><p>This supplied certificate is reproduced without alteration. The document shows its own issue and validity information; no current-certification claim is implied.</p><a className="button button-secondary" href={siteConfig.certificateUrl} target="_blank" rel="noreferrer" onClick={() => track('technical_resource_opened', { location: 'certificate' })}>View certificate <span className="sr-only">(opens in a new tab)</span></a></div></div></div>
        <aside className="evidence-placeholder"><p className="proof-label">Evidence requested for client review</p><h3>Application proof module</h3><p>Approved Puretronics application evidence to be added following client review.</p><ul>{evidenceNeeds.map((item) => <li key={item}><span aria-hidden="true">□</span>{item}</li>)}</ul><small>Placeholder items are excluded from structured data and can be removed without changing the page architecture.</small></aside>
      </div></section>
      <section className="section section-cool" id="service-support"><div className="container about-grid"><div><p className="eyebrow">About Puretronics</p><h2>Wire and cable production and validation capabilities since 1990.</h2><p className="section-lead">Puretronics provides the measurement, testing, process-equipment, tension, control and braking capabilities represented in this profile.</p></div><aside><h3>Existing equipment or a service requirement?</h3><p>For service, spares, calibration, commissioning or support relating to an existing installation, use the dedicated route.</p><a className="button button-secondary" href={siteConfig.serviceSupportUrl} onClick={() => track('service_support_cta_clicked', { location: 'service-section' })}>Go to Service and Support</a></aside></div></section>
    </>
  );
}
