import { families, products } from '../data/catalog';
import { navigatorModes } from '../data/navigatorQuestions';
import { problemOptions, productionStages, projectOptions, requirementDefinitions } from '../data/productionStages';
import { track } from '../analytics/events';
import type { FamilyId, ProjectRoute } from '../types/catalog';
import type { NavigatorMode } from '../types/explorer';
import { useExplorer } from '../state/ExplorerProvider';

function ChoiceButton({ selected, onClick, children }: { selected: boolean; onClick: () => void; children: React.ReactNode }) {
  return <button type="button" className={`choice-button${selected ? ' is-selected' : ''}`} aria-pressed={selected} onClick={onClick}><span className="choice-check" aria-hidden="true">{selected ? '✓' : '+'}</span>{children}</button>;
}

type Discriminator = { id: string; label: string; readinessQuestionId?: string; options: Array<{ id: string; label: string; problemId?: string; readinessOptionId?: string }> };
const familyDiscriminators: Record<FamilyId, Discriminator[]> = {
  PF01: [{ id: 'pf01-need', label: 'Which Measurement Need Is Closest?', readinessQuestionId: 'pf01-function', options: [{ id: 'diameter', label: 'Diameter Measurement', problemId: 'diameter-variation', readinessOptionId: 'diameter' }, { id: 'lump', label: 'Lump-and-Neck Detection', problemId: 'lump-neck', readinessOptionId: 'lump-neck' }, { id: 'unknown', label: 'Not Known Yet', readinessOptionId: 'unknown' }] }],
  PF02: [{ id: 'pf02-method', label: 'Which Test Principle Is Known?', readinessQuestionId: 'pf02-principle', options: [{ id: 'live', label: 'Live AC', readinessOptionId: 'live' }, { id: 'acute', label: 'Acute / High-Frequency AC', readinessOptionId: 'acute' }, { id: 'dc', label: 'DC', readinessOptionId: 'dc' }, { id: 'unknown', label: 'Not Known Yet', readinessOptionId: 'unknown' }] }, { id: 'pf02-response', label: 'Which Fault Information Is Needed?', readinessQuestionId: 'pf02-response', options: [{ id: 'indication', label: 'Fault Indication', readinessOptionId: 'indication' }, { id: 'data', label: 'Logging / Graphics', readinessOptionId: 'logging' }, { id: 'marking', label: 'Inline Marking', readinessOptionId: 'marking' }, { id: 'unknown', label: 'Not Known Yet', readinessOptionId: 'unknown' }] }],
  PF03: [{ id: 'pf03-need', label: 'Which Validation Path Applies?', readinessQuestionId: 'pf03-path', options: [{ id: 'hv', label: 'Offline High-Voltage Testing', problemId: 'offline-hv', readinessOptionId: 'unknown' }, { id: 'fire', label: 'Fire / Circuit-Integrity Testing', problemId: 'fire-resistance', readinessOptionId: 'fire' }, { id: 'unknown', label: 'Not Known Yet', readinessOptionId: 'unknown' }] }],
  PF04: [{ id: 'pf04-need', label: 'Which Process Need Applies?', readinessQuestionId: 'pf04-path', options: [{ id: 'heat', label: 'Conductor Preheating', problemId: 'wire-preheating', readinessOptionId: 'preheat' }, { id: 'powder', label: 'Powder Application', problemId: 'powder-application', readinessOptionId: 'unknown' }, { id: 'join', label: 'Joining / Repair', problemId: 'joining-repair', readinessOptionId: 'joining' }, { id: 'unknown', label: 'Not Known Yet', readinessOptionId: 'unknown' }] }],
  PF05: [{ id: 'pf05-role', label: 'Which Immediate Role Is Needed?', readinessQuestionId: 'pf05-role', options: [{ id: 'indication', label: 'Tension Indication', problemId: 'tension-visibility', readinessOptionId: 'indication' }, { id: 'sensing', label: 'Load / Tension Sensing', problemId: 'load-sensing', readinessOptionId: 'sensing' }, { id: 'control', label: 'Active Control', problemId: 'tension-instability', readinessOptionId: 'control' }, { id: 'braking', label: 'Pneumatic Braking', problemId: 'braking', readinessOptionId: 'braking' }, { id: 'integrated', label: 'Integrated Path', problemId: 'tension-instability', readinessOptionId: 'integrated' }, { id: 'unknown', label: 'Not Known Yet', readinessOptionId: 'unknown' }] }],
};

const knownInputOptions = [['diameter', 'Diameter or Product Size'], ['speed', 'Line or Shaft Speed'], ['voltage', 'Test Method or Voltage'], ['temperature', 'Target Temperature'], ['load', 'Tension or Load'], ['none', 'None Yet']] as const;

export function SolutionNavigator() {
  const { state, dispatch, results } = useExplorer();
  const chooseMode = (mode: NavigatorMode, reset = false) => { if (reset) dispatch({ type: 'CLEAR_FILTERS' }); dispatch({ type: 'SET_MODE', mode }); track('explorer_start_mode_selected', { mode }); };
  const setSingleFilter = (key: 'problems' | 'stages' | 'families' | 'routes', value?: string) => dispatch({ type: 'SET_FILTER_VALUES', key, values: value ? [value] : [] });
  const setAnswer = (questionId: string, value: string | string[]) => dispatch({ type: 'SET_NAVIGATOR_ANSWER', questionId, value });
  const setReadiness = (questionId: string, value: string | string[]) => dispatch({ type: 'SET_READINESS_ANSWER', questionId, value });

  if (!state.navigatorMode) return <div className="navigator-entry" aria-labelledby="starting-point-heading"><div className="view-intro"><div><p className="proof-label">Solution Navigator</p><h3 id="starting-point-heading">Choose Your Starting Point</h3></div><p>You do not need to know a product name. Start with the information already available.</p></div><div className="entry-grid compact">{navigatorModes.map((mode, index) => <button className="entry-card" key={mode.id} type="button" onClick={() => chooseMode(mode.id)}><span className="entry-number">0{index + 1}</span><strong>{mode.title}</strong><span>{mode.description}</span><span className="entry-action">{mode.short} <span aria-hidden="true">→</span></span></button>)}</div></div>;

  const activeFamily = state.filters.families.length === 1 ? families.find((family) => family.id === state.filters.families[0]) : undefined;
  const multipleIssues = state.navigatorAnswers.multipleIssues === 'active';
  const setKnownInput = (id: string) => { setAnswer('knownInputs', id); setReadiness('known-inputs', [id]); };
  return <div className="navigator-panel">
    <div className="navigator-heading"><div><p className="proof-label">Active Route</p><h3>{navigatorModes.find((mode) => mode.id === state.navigatorMode)?.title}</h3></div><button type="button" className="text-button" onClick={() => dispatch({ type: 'CLEAR_FILTERS' })}>Change Starting Point</button></div>

    {state.navigatorMode === 'problem' && <fieldset><legend>What Outcome Do You Need to Improve?</legend><div className="choice-grid">{problemOptions.map(([id, label]) => <ChoiceButton key={id} selected={id === 'multiple-issues' ? multipleIssues : state.filters.problems.includes(id)} onClick={() => { if (id === 'not-sure') { chooseMode('guide', true); return; } if (id === 'multiple-issues') { setAnswer('multipleIssues', multipleIssues ? '' : 'active'); return; } dispatch({ type: 'TOGGLE_FILTER', key: 'problems', value: id }); track('problem_selected', { ids: [id] }); }}>{label}</ChoiceButton>)}</div>{multipleIssues && <div className="guidance-note"><strong>Select Every Applicable Issue.</strong><p>The results use OR logic across the selected issues and explain each matching capability path.</p></div>}</fieldset>}

    {state.navigatorMode === 'family' && <><fieldset><legend>Select One Product Family</legend><div className="family-choice-list">{families.map((family) => <ChoiceButton key={family.id} selected={state.filters.families.includes(family.id)} onClick={() => setSingleFilter('families', family.id)}><span><strong>{family.name}</strong><small>{family.summary}</small></span></ChoiceButton>)}</div></fieldset>{activeFamily && <section className="family-route-detail"><p className="proof-label">{activeFamily.id} · Family Overview</p><h4>{activeFamily.name}</h4><p>{activeFamily.summary}</p><dl><div><dt>Primary Products</dt><dd>{products.filter((product) => product.familyId === activeFamily.id).map((product) => product.shortName).join(' · ')}</dd></div><div><dt>Common Requirements</dt><dd>{requirementDefinitions.filter((requirement) => requirement.productIds.some((id) => products.find((product) => product.id === id)?.familyId === activeFamily.id)).map((requirement) => requirement.label).join(' · ')}</dd></div><div><dt>What to Define</dt><dd>{activeFamily.selectionInputs}</dd></div></dl>{familyDiscriminators[activeFamily.id].map((question) => <fieldset key={question.id}><legend>{question.label}</legend><div className="choice-grid">{question.options.map((option) => <ChoiceButton key={option.id} selected={state.navigatorAnswers[question.id] === option.id} onClick={() => { setAnswer(question.id, option.id); if (option.problemId) setSingleFilter('problems', option.problemId); else if (option.id === 'unknown') setSingleFilter('problems'); if (question.readinessQuestionId && option.readinessOptionId) setReadiness(question.readinessQuestionId, option.readinessOptionId); }}>{option.label}</ChoiceButton>)}</div></fieldset>)}<fieldset><legend>Which Technical Information Is Already Available?</legend><div className="choice-grid">{knownInputOptions.map(([id, label]) => <ChoiceButton key={id} selected={state.navigatorAnswers.knownInputs === id} onClick={() => setKnownInput(id)}>{label}</ChoiceButton>)}</div></fieldset></section>}</>}

    {state.navigatorMode === 'search' && <div className="search-control"><label htmlFor="product-search">Product or Model Name</label><div className="search-box"><span aria-hidden="true">⌕</span><input id="product-search" type="search" value={state.filters.query} placeholder="For Example: AX-400 or LASER-2030" onChange={(event) => dispatch({ type: 'SET_QUERY', query: event.target.value })} /></div><p>Searches only approved product names, model codes and governed aliases.</p>{state.filters.query && !results.length && <div className="guidance-note"><strong>No Approved Record Matched.</strong><p>Continue by Product Family, observed problem or the guided route.</p><div className="inline-actions"><button type="button" className="text-button" onClick={() => chooseMode('family', true)}>Browse Product Families →</button><button type="button" className="text-button" onClick={() => chooseMode('problem', true)}>Start With a Problem →</button><button type="button" className="text-button" onClick={() => chooseMode('guide', true)}>Guide Me →</button></div></div>}</div>}

    {state.navigatorMode === 'project' && <div className="guided-sections"><fieldset><legend>1. Which Project Route Applies?</legend><div className="choice-grid">{projectOptions.filter(([id]) => id !== 'support').map(([id, label]) => <ChoiceButton key={id} selected={state.filters.routes.includes(id as ProjectRoute)} onClick={() => { setSingleFilter('routes', id); setReadiness('project-type', id); }}>{label}</ChoiceButton>)}</div></fieldset><fieldset><legend>2. Which Stages Are in Scope?</legend><div className="choice-grid">{productionStages.map((stage) => <ChoiceButton key={stage.id} selected={state.filters.stages.includes(stage.id)} onClick={() => dispatch({ type: 'TOGGLE_FILTER', key: 'stages', value: stage.id })}>{stage.label}</ChoiceButton>)}</div></fieldset><fieldset><legend>3. Which Outcomes Are Being Improved?</legend><div className="choice-grid">{problemOptions.filter(([id]) => !['multiple-issues', 'not-sure'].includes(id)).map(([id, label]) => <ChoiceButton key={id} selected={state.filters.problems.includes(id)} onClick={() => dispatch({ type: 'TOGGLE_FILTER', key: 'problems', value: id })}>{label}</ChoiceButton>)}</div></fieldset><fieldset><legend>4. What Is the Existing-Equipment Status?</legend><div className="choice-grid">{[['known', 'Existing Equipment Is Known', 'documented'], ['partial', 'Partly Known', 'partial'], ['none', 'No Existing Equipment', 'none'], ['unknown', 'Not Known Yet', 'unknown']].map(([id, label, readinessId]) => <ChoiceButton key={id} selected={state.navigatorAnswers.existingEquipment === id} onClick={() => { setAnswer('existingEquipment', id); setReadiness('existing-equipment', readinessId); }}>{label}</ChoiceButton>)}</div></fieldset></div>}

    {state.navigatorMode === 'guide' && <div className="guided-sections"><fieldset><legend>1. Where Is the Requirement?</legend><div className="choice-grid">{[['line', 'Production Line'], ['lab', 'Offline Laboratory / Test Area'], ['unknown', 'Not Known Yet']].map(([id, label]) => <ChoiceButton key={id} selected={state.navigatorAnswers.guideLocation === id} onClick={() => { setAnswer('guideLocation', id); const stageIds = id === 'lab' ? productionStages.filter((stage) => stage.kind !== 'inline').map((stage) => stage.id) : id === 'line' ? productionStages.filter((stage) => stage.kind === 'inline').map((stage) => stage.id) : []; dispatch({ type: 'SET_FILTER_VALUES', key: 'stages', values: stageIds }); setReadiness('requirement-location', id === 'lab' ? 'laboratory' : id); }}>{label}</ChoiceButton>)}</div></fieldset><fieldset><legend>2. What Is the Broad Concern?</legend><div className="choice-grid">{[['PF01', 'Dimensional Quality'], ['PF02', 'Insulation Faults'], ['PF03', 'Electrical / Fire Testing'], ['PF04', 'Process Preparation'], ['PF05', 'Tension / Braking'], ['unknown', 'Not Sure']].map(([id, label]) => <ChoiceButton key={id} selected={state.navigatorAnswers.guideConcern === id} onClick={() => { setAnswer('guideConcern', id); setSingleFilter('families', id.startsWith('PF') ? id : undefined); }}>{label}</ChoiceButton>)}</div></fieldset><fieldset><legend>3. What Is the Project Context?</legend><div className="choice-grid">{[['new-line', 'New Project'], ['retrofit', 'Existing-Line Problem'], ['replacement', 'Replacement'], ['unknown', 'Not Known Yet']].map(([id, label]) => <ChoiceButton key={id} selected={state.navigatorAnswers.guideProject === id} onClick={() => { setAnswer('guideProject', id); setSingleFilter('routes', id === 'unknown' ? undefined : id); setReadiness('project-type', id); }}>{label}</ChoiceButton>)}</div></fieldset><fieldset><legend>4. Which Basic Measurement Is Known?</legend><div className="choice-grid">{[['diameter', 'Diameter'], ['speed', 'Line Speed'], ['load', 'Tension / Load'], ['voltage', 'Test Method / Voltage'], ['temperature', 'Temperature'], ['none', 'None Yet']].map(([id, label]) => <ChoiceButton key={id} selected={state.navigatorAnswers.guideKnown === id} onClick={() => { setAnswer('guideKnown', id); setKnownInput(id); }}>{label}</ChoiceButton>)}</div></fieldset><div className="guidance-note"><strong>Useful Result First</strong><p>The result set is constrained by location, concern and project context. The known measurement is carried into the Application Review so the next relevant V4-derived band can be answered there.</p></div></div>}
  </div>;
}
